>gi|332003433|gb|AED90816.1| translocase of chloroplast 34 [Arabidopsis thaliana]
MAALQTLREWIGIQQFPPA-TQSKLLEILGKYKEEDVSSL--------TVLVMGKGGVGK
SSTVNSVIG-----EKAAAVSTFQSEGLRPTLVSRTRSG--FTLNIIDTPGLIE--GGYV
NDQAI-------NIIKRFLLNMTIDVLLYV---DRL---DVYRVDDLDRQVVGAITDAFG
KEIWKKSALVLTHAQFSPPDGLNYNHFVSKRSNAL----LKVIQTGAQLKKQDLQGFSIP
VILVEN-SGRCHKNESDEKILPCGTSWIPNLFNKITEISFNGNKAIHVDKKLVEGPNPNE
RGKKLIPLMFA-----------FQYLLVMKPLVRAIKSDVSRESKPAWELRDSG------
LASRRS
>Ectocarpus_siliculosus_gi|298704916|emb|CBJ28419.1| conserved unknown protein [Ectocarpus siliculosus]
MAEMAT-------TLLPMAWDASKKAYNLAKSNNIDGWSFPGNPKRARKILVAGLAGSGK
TSVINSLTGLNLETGDSSQGVTFQCSAVPERIYRKDVSGEPVKLVFMDTVGFDSGPGGAL
GDGALHRDMAFTSMMKLLRATSELDVIIYVMEKGRLTTGDMTCYELLVKKVAHGLRRSDG
V-IDQKIPVILVVTKCETRPSTNLQSWLGQRAASVPVPGVDMVVNGTNHQVLNNAGMDTS
RILCAAFFGDDHFAAGSPDGIACRNDSVRSLLKLIVGCSDDG------------------
------PFLAAHPGNFFRETNVFRYML--SPSYRKNNKDKFLKYLKGVFPRDDAEKIFAQ
VIDYKK
