>Arabidopsis_thaliana_gi|332189644|gb|AEE27765.1| translocon at the inner envelope membrane of chloroplasts 20 [Arabidopsis thaliana]
MITGYSTPSAHVLMSSRAFKSSSYRAAAGQTQHYLARSSLPVVKNSWGSPPSPFNELPRV
SRGVPLSYLSASSSLLLNGEQGSLSGTLPVLPVRRKTLLTPRASKDVPSSFRFPPMTKKP
QWWWRTLACLPYLMPLHETWMYAETAYHLHPFLEDF-EFLTYPFLGAIGRLPSWFLMAYF
FVAYLGIVRRKEWPHFFRFHVVMGMLLEIALQVIGTVSKWMPLGVYWGKFGMHFWTAVAF
-----AYLFTVLESIRCALAGMYADIPFVCDAAYIQIPYD
>Ectocarpus_siliculosus_gi|298713221|emb|CBJ33519.1| conserved unknown protein [Ectocarpus siliculosus]
M------------------KASGQGGGKGES-----------VRN---------------
------------------------------------------------------------
----RALGTVVYLLPMLDGLDCGRDVFHAVPMLGSLVHGVLAPALAIWDNVP--FMPLVM
FIILQVSVRRQDTSRFIRFNVQQAILVDILTVVLGLLGT---AAGYVAPEGEQFVTNFAF
YCLVGAVAYAVAETARGKMAN---QIPLISAAAEIQLGPS
