>gi|75335547|sp|Q9LVH5.1|OE64C_ARATH RecName: Full=Outer envelope protein 64, chloroplastic; AltName: Full=Translocon at the outer membrane of chloroplasts 64-III
MASQAANLWVLLGLGLAGILMLTKKLKKTVREDFGAFIDKLMLLPPPQPAPPKAPHPLTG
LTFAVSDVFDITGYVTGFGHPDWVRTHEAASSTSPVVSTLVEGGATCVGKTVVDEFAFSI
SGENKHYDSPTNPAAPTRIPGGACSGAAVAVATNAVDFALGIDTVGGVRVPAGYCGVLGF
KSSYGAISNTG--------------IIPVSSS----------------------------
--------------------LDSVGWFARDPNTLRRVGHVLLQLPFATQRNPRQIILADD
CFQL-LKIPVDRITQVVTKSAEKLFGRQLLK-----HQ--NLETYFETKVPSLKEFARTK
AIA---NTKVSTSRLLANVMQLLQRHEFLQNHGDWINTVKPAIDPVILSQVCENPELTNE
ETENLNAIRNETRVAIGSLLK-DDGILVIPTLPAVPPKLGSKEITSEDYQNRASSLLSIA
SISGCCQVTVPLGHHEKCPISVSFIGRHGGDRFLLDTVQTMYPSLQEYSSIVTDPKSSKK
AITKEESAEIAKEKGNQAFKEKLWQKAIGLYSEAIKLSDNNATYYSNRAAAYLELGGFLQ
AEEDCTKAITLDKKNVKAYLRRGTAREMLGDCKGAIEDFRYALVLEPNNKRASLSAERLR
KFQ
>Phaeodactylum_tricornutum CCAP 1055/1_gi|219119326|ref|XP_002180426.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
--------------------------------------------------------PLYG
VPISVKEHLALRGSYSTGGLA--CRLNQKDTKDSLIVQVIRSAGAIPMCSGNVPQIMMLP
ETYNRIWGRSRNPWDLCRSTGGSSGGDAALVAARCVPLAIGSDVAGSIRIPASFCGIVGF
KPTAYRVSGKGNMKARKNNRSGTSAVIPVVCGPLARTVDDCAQFMKAVLVPEMFQGDSSV
PPLPFDVDSYQSKAKLKIGYFDTDGWFEPCLTSKRAVREAIDALTKAGHTCVPFKLPTDG
WISYGLLVAINAAEGNFRSFVEALEGEQMISEYDTLHQASNLPNLLKPVIMALIDKRRGH
LLKQGRNGGVPVWDLWQSVAKVLELRQ------KWDNAVREAGLDAIVHPAMPIPAIQHG
LSGKLTA--SCSYMFLANLLQWPSGALPVTTVRADEAHYRRKDMPAD--QRDIISRIVAQ
VMQG----------SEGMPISVCVMSPSYRDETCLRVMKEIEKTI----PFQEEPKAFLK
A-----------------------------------------------------------
------------------------------------------------------------
---
