>>gi|75221490|sp|Q43715.1|TOC75_PEA_RecName: Full=Protein TOC75, chloroplastic; AltName: Full=75 kDa chloroplast outer envelope protein; AltName: Full=75 kDa translocon at the outer-envelope membrane of chloroplasts; AltName: Full=Import intermediate-assoc_gi|75221490|sp|Q43715.1|TOC75_PEA RecName:
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RTSVIPNRLTPTLTTHPSRRRNDHITTRTSS
LKCHLSPSSGDNNDSFNSSLLKTISTTVAVSSAAASAFFLTGSLHSPFPNFSGLNAAAGG
GAGGGGGGSSSSGGGGGGWFNGDEGSFWSRILSPARAIADEP--KSEDWDSHELPADITV
LLGRLSGFKKYKISDILFFDRNKKSKVETQDSFLDMVSLKPGGVYTKAQLQKELESLATC
GMFEKVDMEGKTNADGSLGLTISFAESMWERADRFRCINVGLMGQSKPVEMDPDMSEKEK
IEFFRRQEREYKRRISSARPCLLPTS-------VHEEIKDMLAEQGRVSARLLQKIRDRV
QSWYHEEGYACAQV----------VNFGNLNTREVVCEVVEGDITKLSIQYLDKLGNV--
------------------------------------------------------------
--VEGNTEGPVVQ----------RELPKQLLPGHTF----NIEAGKQALRNINS------
------LALFSNIEVN---PRPDE-----------MNEGSIIVEIK--LKELEQKSAEVS
TEWSIVPGRGGRPTLASLQPGGT-------------------------------------
--ITFEHRNLQG-----------LNRSLTGSVTTSNFLNPQDDLAFKMEYAHPY---LDG
VDNPRNRTLRVSCFNSRKLSPVFT----------GGPGVDEVPSIWVDRAGVKA------
------------NITENFSRQSKFTYGLVMEEIITRDES--------------------N
HICSNGQRVLPNGAISADGPPTTLSGTGID----------------------------RM
AFLQANITRDNTRFVNGTIVGSRNMFQVD---QGLGVGSNFPFFNRHQLTVTKFLQLM--
------------------------------SVEEGAGKSPPPVLVLHGHYGGCVGD----
----------------------------LPSYDAFTLGGPYSVRGYNMGEIGAARNI---
------------------------------------------------------------
-LELAAEIRIPIK---------GTHVYAFAEHGTDLGSSKDVKGNPTVVYRRMGQG----
----------------SSYGAG-----MKLGLVRAEYAVDHNSGTGAVF-----------
-------------------------------------------FRFG-------------
ERF---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Thalassiosira_pseudonana_gi|295792214|gb|ADG29122.1| plastid Omp85-like protein [Thalassiosira pseudonana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ITFQTTRRKYPLLGGLACCLCLRAFVHISGDTSHPS-------------
--------------------------IFANQHIGCDAFSLPPS---------RLRHTRGV
YRGGAFGRSGNAGGGNNG---GRRPTLHFNHFYDDDSDSNGGV----D------------
-MNVLQLLWMSTSSDNE---SNYISEHYTSSA--ACVNLRGGGGVK--------------
--------ETGNNPLQKLGSA---------------------V--SRHIP-----FQQNK
KEQSNLQEQEKLLSITHVTSVCAPSSDLLPLEVITQSSKQANLIGGTLTPETMERTASLI
NQWYWNQGYVMNSVTGATLVPGKANEGGGKVELKVREVKLAKSRSSVDIRFVDRCDNANT
EAGVEIIT--------------------------------LPAQTNDHQVQNSDSFPQYQ
KYKL------TSG----------RTRPLKVARMVQLSPGSQFRILPERWSRLVALPGGTF
GGGGGKSAIFSAIHAVQ--PVPTK-----------DGKDTVNIEIL--ASE---NK----
-------------PYVSMEYGVTKSLYSDQWEG---------------------------
-ELDLKHGNTFGGGEVATLNSFN-DEKLGRSIDGGTFEL--ED-EYQ------RYAF---
-G--------------------------------GGDSGYDV-QIFRDHLGVSGMMNDVK
DEQVHEEDCP---------QRTGASIRLRLP---KQTLP--------------------H
AVSASFERI--NQSISAPTASRT---QSMAS----ATMKIGPCRCGES--FLKRSFHNVR
SALSASITAGA--RWDAASTSSETATV---D------TKTRPY-ATGTITSQHIIPLV--
------------------------------SYPFGNRDNGTVNFAMRHVLSAASMH----
----------------------------LPRHEAIILGLASRVRGYKYNYQSHSLQP---
-----------------------------QKIVAKQVQRSWKFLQGSSDGQTRPPIAVSK
AISGTMEIRVPLH--------PLSK-RDESNLGTEGSLSSILSGDM-VLFGDWSISQAQT
QSSSHQDQYDTSLLRHSSIGIGFR---KRVQGIPLKMDACIT-EHGA-------------
--------------RGVF-------------------------FGIG-------------
----Q-------------------------------------------------------
------------------------------DFGV--------------------------
------------------------------------------------------------
----------------------------------------
