>>gi|75221490|sp|Q43715.1|TOC75_PEA_RecName: Full=Protein TOC75, chloroplastic; AltName: Full=75 kDa chloroplast outer envelope protein; AltName: Full=75 kDa translocon at the outer-envelope membrane of chloroplasts; AltName: Full=Import intermediate-assoc_gi|75221490|sp|Q43715.1|TOC75_PEA RecName:
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------RTSVIPNRLTPTLTTHPSRRRNDHITTRTSS
LKCHLSPSSGDNNDSFNSSLLKTISTTVAVSSAAASAFFLTGSLHSPFPNFSGLNAAAGG
GAGGGGGGSSSSGGGGGGWFNGDEGSFWSRILSPARAIADEP--KSEDWDSHELPADITV
LLGRLSGFKKYKISDILFFDRNKKSKVETQDSFLDMVSLKPGGVYTKAQLQKELESLATC
GMFEKVDMEGKTNADGSLGLTISFAESMWERADRFRCINVGLMGQSKPVEMDPDMSEKEK
IEFFRRQEREYKRRISSARPCLLPTS-------VHEEIKDMLAEQGRVSARLLQKIRDRV
QSWYHEEGYACAQV----------VNFGNLNTREVVCEVVEGDITKLSIQYLDKLGNV--
------------------------------------------------------------
--VEGNTEGPVVQ----------RELPKQLLPGHTF----NIEAGKQALRNINS------
------LALFSNIEVN---PRPDE-----------MNEGSIIVEIK--LKELEQKSAEVS
TEWSIVPGRGGRPTLASLQPGGT-------------------------------------
--ITFEHRNLQG-----------LNRSLTGSVTTSNFLNPQDDLAFKMEYAHPY---LDG
VDNPRNRTLRVSCFNSRKLSPVFT----------GGPGVDEVPSIWVDRAGVKA------
------------NITENFSRQSKFTYGLVMEEIITRDES--------------------N
HICSNGQRVLPNGAISADGPPTTLSGTGID----------------------------RM
AFLQANITRDNTRFVNGTIVGSRNMFQVD---QGLGVGSNFPFFNRHQLTVTKFLQLM--
------------------------------SVEEGAGKSPPPVLVLHGHYGGCVGD----
----------------------------LPSYDAFTLGGPYSVRGYNMGEIGAARNI---
------------------------------------------------------------
-LELAAEIRIPIK---------GTHVYAFAEHGTDLGSSKDVKGNPTVVYRRMGQG----
----------------SSYGAG-----MKLGLVRAEYAVDHNSGTGAVF-----------
-------------------------------------------FRFG-------------
ERF---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Thalassiosira_pseudonana_gi|295792214|gb|ADG29122.1| plastid Omp85-like protein [Thalassiosira pseudonana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------ITFQTTRRKYPLLGGLACCLCLRAFVHISGDTSHPS-------------
--------------------------IFANQHIGCDAFSLPPS---------RLRHTRGV
YRGGAFGRSGNAGGGNNG---GRRPTLHFNHFYDDDSDSNGGV----D------------
-MNVLQLLWMSTSSDNE---SNYISEHYTSSA--ACVNLRGGGGVK--------------
--------ETGNNPLQKLGSA---------------------V--SRHIP-----FQQNK
KEQSNLQEQEKLLSITHVTSVCAPSSDLLPLEVITQSSKQANLIGGTLTPETMERTASLI
NQWYWNQGYVMNSVTGATLVPGKANEGGGKVELKVREVKLAKSRSSVDIRFVDRCDNANT
EAGVEIIT--------------------------------LPAQTNDHQVQNSDSFPQYQ
KYKL------TSG----------RTRPLKVARMVQLSPGSQFRILPERWSRLVALPGGTF
GGGGGKSAIFSAIHAVQ--PVPTK-----------DGKDTVNIEIL--ASE---NK----
-------------PYVSMEYGVTKSLYSDQWEG---------------------------
-ELDLKHGNTFGGGEVATLNSFN-DEKLGRSIDGGTFEL--ED-EYQ------RYAF---
-G--------------------------------GGDSGYDV-QIFRDHLGVSGMMNDVK
DEQVHEEDCP---------QRTGASIRLRLP---KQTLP--------------------H
AVSASFERI--NQSISAPTASRT---QSMAS----ATMKIGPCRCGES--FLKRSFHNVR
SALSASITAGA--RWDAASTSSETATV---D------TKTRPY-ATGTITSQHIIPLV--
------------------------------SYPFGNRDNGTVNFAMRHVLSAASMH----
----------------------------LPRHEAIILGLASRVRGYKYNYQSHSLQP---
-----------------------------QKIVAKQVQRSWKFLQGSSDGQTRPPIAVSK
AISGTMEIRVPLH--------PLSK-RDESNLGTEGSLSSILSGDM-VLFGDWSISQAQT
QSSSHQDQYDTSLLRHSSIGIGFR---KRVQGIPLKMDACIT-EHGA-------------
--------------RGVF-------------------------FGIG-------------
----Q-------------------------------------------------------
------------------------------DFGV--------------------------
------------------------------------------------------------
----------------------------------------
>Thalassiosira_pseudonana CCMP1335_gi|223993387|ref|XP_002286377.1| predicted protein [Thalassiosira pseudonana CCMP1335]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-MNVLQLLWMSTSSDNE---SNYISEHYTSSA--ACVNLRGGGGVK--------------
--------ETGNNPLQKLGSA---------------------V--SRHIP-----FQQNK
KEQSNLQEQEKLLSITHVTSVCAPSSDLLPLEVITQSSKQANLIGGTLTPETMERTASLI
NQWYWNQGYVMNSVTGATLVPGKANEGGGKVELKVREVKLAKSRSSVDIRFVDRCDNANT
EAGVEIIT--------------------------------LPAQTNDHQVQNSDSFPQYQ
KYKL------TSG----------RTRPLKVARMVQLSPGSQFRILPERWSRLVALPGGTF
GGGGGKSAIFSAIHAVQ--PVPTK-----------DGKDTVNIEIL--ASE---NK----
-------------PYVSMEYGVTKSLYSDQWEG---------------------------
-ELDLKHGNTFGGGEVATLNSFN-DEKLGRSIDGGTFEL--ED-EYQ------RYAF---
-G--------------------------------GGDSGYDV-QIFRDHLGVSGMMNDVK
DEQVHEEDCP---------QRTGASIRLRLP---KQTLP--------------------H
AVSASFERI--NQSISAPTASRT---QSMAS----ATMKIGPCRCGES--FLKRSFHNVR
SALSASITAGA--RWDAASTSSETATV---D------TKTRPY-ATGTITSQHIIPLV--
------------------------------SYPFGNRDNGTVNFAMRHVLSAASMH----
----------------------------LPRHEAIILGLASRVRGYKYNYQSHSLQP---
-----------------------------QKIVAKQVQRSWKFLQGSSDGQTRPPIAVSK
AISGTMEIRVPLH--------PLSK-RDESNLGTEGSLSSILSGDM-VLFGDWSISQAQT
QSSSHQDQYDTSLLRHSSIGIGFR---KRVQGIPLKMDACIT-EHGALAKTNAVAFAHYL
LPPSMIRATEVLLPRVVFSSVAPKTSELSDTSTEPINSPAHPSFSVR-------------
----QRPFPSLFNNFVRTNDVPALLEEFDKLTQTRMNRWLLSPQHNFSFPSLPMWDLSSF
ASTGWNNAKFDDASNTWSVPMKVPNIFRTEDIAVKVVKEPSGHYVLRITGRREMENTTDK
GETNEPSGMDVEATDTKSDLPASKSNYHYEMKLHFPPQDNMTEGDLTEYFSKITSELNKD
EGLLTVKIPDDIVSPNKGGSTIARENAENEIFSVPIQAVA
>Phaeodactylum_tricornutum CCAP 1055/1_gi|219121419|ref|XP_002185934.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------KTSSLVPLL------------------------------------
--------------------------LLALIVPECQAF-LPPS-----------------
----------NSPRGRIG---G----LFSQPFTDGRNSGDNGVPPSDD------------
-IGHLQAWDGFEGPTLL---ASIIRKNDTDAP--S--GLRGGGDVV--------------
--------KGTQ---ATLSST---------------------A--KKKVA-----NSFKS
KEVKKEEELLHQLKNMPIQRVVVPNSTVLPNEVIQLAANRAGVVGHPLQSTSIQSFAKSL
KEWYIRKGYILHSVTGATL-----QSETGTAIITVQE--PAVSKDPVGITFCK--EMVVD
EETGNLLT--------------------------------FRQYKDKHQNRRTLGFDKIT
KADLNTTFVPTAG----------HTRPNRIASALGLSPGNPFQWDGIRWQQIAS------
------SGIFAQVLRAT--PQPMQ-----------DG--TVQLHIL--ATE----A----
-------------PTRHLEYGLGKSLYTGSWEG---------------------------
-ELDFEHINLLGGG-----------ESLGLSVRRGTKDA--EP-SIRLSFTDSKFGL---
-G--------------------------------G---GYDL-EVFSDFIG-------DQ
PEEMQEGELPPDYDHDSILDRKGATVRLRNPICSRIVRN--------------------S
VASGSLER----------TATKTGLHETIGS----TTLAVGP--------FVKRLPYDAR
SSIDAKCSLGT--RLFAASSTTEEANALLPP------LKLKPY-TSATATTRQIFPLLA-
------------------------------SFGPGGR---PLILALKHSITTATPN----
----------------------------LPRHEAKAQGIAHNIRGSSLNGR---------
---------------------------------------------------------VAS
ALTGTTELRVPID-------IPVVQIRQDTN--------------V-VFFGDWLFAAKDS
QS---------SFRRKSCVGVGVR---KSVQGIPLKYDLCYSSDDGK-------------
-----------------FQSA----------------------FGLG-------------
----A-------------------------------------------------------
------------------------------DFDF--------------------------
------------------------------------------------------------
----------------------------------------
>Phaeodactylum_tricornutum_gi|295792212|gb|ADG29121.1| plastid Omp85-like protein [Phaeodactylum tricornutum]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------KTSSLVPLL------------------------------------
--------------------------LFALIVPECQAF-LPPS-----------------
----------NSPRGRIG---G----LFSQPFTDGRNSGDNGVPPSDD------------
-IGHLQAWDGFEGPTLL---ASIIRKNDTDAP--S--GLRGGGDVV--------------
--------KGTQ---ATLSSTSSYWAKAFQSFRGAVVKPLIEA--KKKVA-----NSFKS
KEVKKEEELLNQLKNMPIQRVVVPNSTVLPNEVIQLAANRAGVVGHPLQSTSIQSFAKSL
KEWYIRKGYILHSVTGATL-----QSETGTAIITVQE--PAVSKDPVGITFCK--EMVVD
EETGNLLT--------------------------------FRQYKDKHQNRRTLGFDKIT
KADLNTTFVPTAG----------HTRPNRIASALGLSPGNPFQWDGIRWQQIAS------
------SGIFAQVLRAT--PQPMQ-----------DG--TVQLHIL--ATE----A----
-------------PTRHLEYGLGKSLYTGSWEG---------------------------
-ELDFEHINLLGGG-----------ESLGLSVRRGTKDA--EP-SIRLSFTDSKFGL---
-G--------------------------------G---GYDL-EVFSDFIG-------DQ
PEEMQEGELPPDYDHDSILDRKGATVRLRNPISSRIVRN--------------------S
VASGSLER----------TATKTGLHETIGS----TTLAVGP--------FVKRLPYDAR
SSIDAKCSLGT--RLFAATSTAEEANALLPP------LKLKPY-TSATATTRQIFPLLA-
------------------------------SFGPGGR---PLILALKHSITTATPN----
----------------------------LPRHEAKAQGIAHNIRGSSLNGR---------
---------------------------------------------------------VAS
ALTGTTELRVPID-------IPVVQIRQDTN--------------V-VFFGDWLFAAKDS
QS---------SFRRKSCVGVGVR---KSVQGIPLKYDLCYSSDDGK-------------
-----------------FQSA----------------------FGLG-------------
----A-------------------------------------------------------
------------------------------DFDF--------------------------
------------------------------------------------------------
----------------------------------------
>Phytophthora_infestans T30-4_gi|301117374|ref|XP_002906415.1| sorting and assembly machinery component 50 [Phytophthora infestans T30-4]
MASTNSEAP---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EPTAEPPHPWGPQIHIGKVF
LKGNERTKPEVFE----------NEL-QEAYSAKRI--GRLVRNLEEATEELKA------
------LDIFESIDIKL--DKASS-----------GERDETDITIT--VKE----K----
-------------GWRSLHVGAT---TDGSDEAG--------------------------
-ESTLTLSNALG-----------EAEKITLSATYA-RSG--SN-TQRATFKKPR-FL---
-GLPL--YL-------------------------SAIGTNELH-----------------
---------NQEWLSSYSEKIRAGSISISDY---EGVHD--------------------L
SLNVGWRDLLPRRDAKVP----TAYRASPS--------------------ILAEAMPSTK
TSVKYVFTDDN--RNNVVYPTAGGLFKYTTEIAGL--VGDVKF-VKAEVEGQKH-----V
------------------------------AVGPNVFGFPILNFSLSCHLGTVKSY----
---------------------GNEQHRPARISDRFFLGGPMNVRGFNHKGIGPRASP---
---------------------------------------------LDGGVAQGDALGGDV
SYNGTASVGFPVP--LPLLAALGLRGQLFANAGNLTTWDRLLDEKK-WM-KNLADDTR--
----------------VSIGLGLVWG-TRIGRLEANYSWILKAHDHD-NIKRA-Q-----
-------------------------------------------LGLG-------------
MTF-C-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Albugo_laibachii Nc14_gi|325181532|emb|CCA15982.1| sorting and assembly machinery component 50 putativ [Albugo laibachii Nc14]
MRFSVAHATHKSFQSTNLLTVKNVPVPGSKSTSPIPAKICMLQFLYEIITHLPENQSQIW
LLDELRRFIHKLRQYRHLLSKLQSQDLFFSRVQIWNKSVTETREKFLALYQIHLTNQCGL
TRSNETRRTEHSLRLEVLSEIFIDYHARQLNLIDITTMCTSGWSSVQVQQLLSFLVQTCS
LHDTCEMPELVVQLCDFLNQTGPSIWRKLQSIQKEYQDQLTKTLSLQASEISIYFEDPQA
QLRQILVADWNNAKDIWATGIRCIRRLCLEYPAARRKRNGKQLSPLHNTTQVSPIMTSSS
NELTMQKAPSPGHDYSGLLHAISRETDWRSQLTYRVCKAMSQHVSLFQAHRYTAFYNEVT
KAVPEIERFELILKGNLILSKIMTQHDFLDHFGNRAPQHVLKEVVESFAGLNHDDSSATS
ASRLICESSQVDENGHCCDKSGPCASHCDIHALGSRARNVPKRNQLKRRCQSHQNSTELT
TRPLENQRCRYVSQSPEPEQAAEDHTLACTTVIPGEISNGPQDSTIVGNGIQGEDRNQRK
HIGYLEQLWMDLIEPVEQDTALLMQENAKIFRWLLLFGLATLLGKQYTKYSPKWQSKSNE
NDGIGLGTRPGEIYNARVGEFNVELQIMWSFHCETKLWTTHKHWLKYLHLIRNKEFVVVT
WTELTDHILEIKQEWESNQALRHFDPRRVYWENHFRQQVSRSHRNTFRDSEGIIDELDRF
YENTITLVKLNSRDIDDYTLERIVRLKALQKIDLHHPPNRDRFLQDSNQTTIWSLFLQLL
QRQRMVNQLGFYHGKLQNAQLIDLSIALSSRVEKFGPTAEISRFELVSIKLADDCLSNGA
PLHCVTESNVVSTLCATIAKLQFLENLRISNSLFTCEGTDMEKVTAELLYTAFHLPRLKS
LCLEHADMPDNVFKKALRSLLFPATTSLCSITTIHFGDNCITAQTLRMLGLIISTKGWKL
KRLDLQGSMNIGDSGIPCLIPILADSGLCVLEDLNLRNCGLGIDGARMLCTALETNQSVQ
RMNISHNFLSPVFGGSLASLLQHNTTINALHCDYIGLTDVGCTDELILAIQNNLALNEIT
LGVNRLGDNGSSKVFDALVKRSLRKPYIKIDLSGNIITSLGLH--RMQLA-----LRQQI
QSDSELMDQLQYTRFELIIGATYRVL----------------------------------
------------------------LKHNTVPANPLVLWCFKGTTVFISVAWKMS------
----------------------------------------SEDDDMTYLLGPKMHIRNIF
LTGNDRTRAELFD----------REL-ADAIEAEYI--GQIFGSLEQSLRELTA------
------LDIFTSIDVKL--DKGME-----------CRDDEVDVYIN--VKE----K----
-------------SWRKIKIGAT---TDGSEETA--------------------------
-ETSCTLTNAFG-----------NAERLTLSASYG-RTG--SN-TEAATLVQPR-FM---
-GLPL--TL-------------------------SINATNELH-----------------
---------THEAFSSYSEKVRGALVALCDE---FGRHE--------------------L
SLHCGWRDIIPKRDKTIP----TIFHASPS--------------------ILAQAQPSVK
TSVKYSFNDDD--RDDPMLPCFGSLLHCSTEIAGL--YGDVKF-VKTEVSAQKH-----T
------------------------------SFGPTMFQLPLLNFSLSSRFGLLKTV----
---------------------RDNQEQDSRISDRFFLGGPLSLRGFHYKGVGPRASP---
---------------------------------------------TQGGVPSGDSLGGDL
FYTASAHVGFPFP--FPMLAMLGLRGQVFGSIGNLTTWDRVLHKKR-WM-RNLANDTR--
----------------VSIGMGLVLP-SSFGRLEASYSWIISALKHD-HIRRG-Q-----
-------------------------------------------IGIGSRQRRYLAYMTSH
PAC-Q-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Ectocarpus_siliculosus_gi|298713215|emb|CBJ33514.1| Sorting and Assembly Machinery 50kDa protein (N-terminal) [Ectocarpus siliculosus]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------VIP------
----------------------------------------LDELP--------LRVRTVK
IVGNNRTKPYVVE----------DQL-QDAYEATTV--GDVYGGLVEGAQRLDG------
------LGLFESVQVSM--DAVDD-----------GSLDQTDVTVT--VKE----K----
-------------NWYLLQSGAT---TTGTAKGN----------------LDASEFSNLR
YSVAGALRNPLG-----------HGEMLDVGYNSP-IKGQEGH-TVSAKLHLPH-LF---
-RTPVSGTL-------------------------EAIMDTVVF-----------------
---------EDENTRQEHWTLTVERHASSDV---ETRQ----------------------
----------AKRITAIR----TALSTASCYDQTLLLLLLLLLLLLLLLLLLLLLLPS--
-------------------PPVGDTHTFGMRI-GL--MGDTSF-AKGMLEMQRHIPLFGV
------------------------------ELGPETY--SPVTLSLCASGGAIRPF----
---------------------GPSKR--TFFSDRFNLGGPMTLRGFPFYGAGPRSPK---
---------------------------------------------EEGGCEGGDALGGDI
RYTASASLGFPFP--VPAMATAGWRGYLFTNLGNLTTWDTP-------L-KQYGRDTR--
----------------VSVGVAAAWNFLGVGRLEINYAHVLRRSPRDLHRERPLQ-----
-------------------------------------------FGFG-------------
VSF-E-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Aureococcus_anophagefferens_gi|323454251|gb|EGB10121.1| hypothetical protein AURANDRAFT_62685 [Aureococcus anophagefferens]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------D------
----------------------------------------ISAEP--------CTCSGVE
VVGLTRTRPYVIT----------EAF-QQ--NTRTF--GELLKSVDSGVKALEA------
------TDLFSSVSASLREDKGHP-----------G-ATAAKVTVR--VAE----K----
-------------QPYALKVGATTTPTNGNDVTF--------------------------
-ESSATLRSLLG-----------HGELATATLNQS-TQQ--NH-EIQVSLKK-R-VA---
-GGRV---L-------------------------EA-AFNEGA-----------------
---------GEAPWAPGAAETRAQQLGTT-------AAR--------------------L
SLGANWFAEWSRRA------------------------------------GLQDGSLSDK
WSLSYGGSSES--RDVPQAPTTGAAAHHRVEVAGVGGLGDAAF-VKAEAGAQAH-----A
------------------------------RLAATAN--GFVAASVAARVGAMVGLPLLL
RENIFKDVSDVPPIATALAPPTNGASLPLHKPDKFYLGGPSALRGFDRCGVGARKPPGLD
PAAADRPQRAPSVLLRAWRDMRSPSAPAESAADAWDPHAAEATTDDDALPFAGAATGGTL
FYAAAALLSAPLP---GAPGAQGARGHVFANAGGLVDADLLYAGPR-ALAKDLAHETR--
----------------AAAGVGLSFAPANFARLELNYAWVLRAQQCD-LVKRL-Q-----
-------------------------------------------FAIT-------------
GSFGS-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Thalassiosira_pseudonana CCMP1335_gi|224002020|ref|XP_002290682.1| predicted protein [Thalassiosira pseudonana CCMP1335]
MNNNHQQRRQGGDASSA-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------SSAIS--HQQRL-----QRHRQ
QQQQQMMEKLNQLKAQYVSDYSLPLN----------------------------------
------------------------YPAN--------------------VTSLLD------
----------------------------------------ASDDNTSDASKSKQNEPSLL
RTDQDFINARLLEAGVPLGGGVPDLT-PTSQSKMTI--TDHNASIARFIHDLEG------
------TGCYDAVQVYL--GNNNEVSTSGNQDDGATSTDSFDVTVR--LKE----K----
-------------KWYKLYIGGG---VNSEDLSSFGGTSGMGNTLGGPGGAALGILPKLQ
FETSASLLNLTG-----------FADVSTALYSVD-QTG--AS-SFKFTHDRPL-CS---
-WLPKHSSIREWLMPPDPRLIDPEERNASNGQSADSVDENQVFVADDAQYSLGGGSHTSL
GIHAMVHDLDFESTRSSKEFVRSIGVRLANH---CRGAAGGSNKPGVSPPEAMAGPYLFL
DWNASLRDTMPRRNAEFP----FALDCSKE--------------------VASQAGTVFK
HSLTGGMYLNGCFTDDRYDPTMGYDAHVLGEVAGP--PGDVGF-WKLKGGGSWHLPLELI
GMMAFGVNEEEYTSKEEDESPVVIGATLHSSFNAGLI--RPLSFSGLCNSGSIGGV----
-----------------------------PSSDKFYVGGPGQLRGFLPSGIGPRSAK---
---------------------------------------------GGSSVPGGDSLGGDV
YYTTTLAGSIPFPSYFATLRQNGARVFGFTNVGTCVSTGGSVLGMP-AF-SQILQSSR--
----------------VAVGGGVSVG-SPMGRFEATYAVPMRYGPRD-ATKAV-Q-----
-------------------------------------------FGFG-------------
FSF-G-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Blastocystis_hominis_gi|300122635|emb|CBK23203.2| unnamed protein product [Blastocystis hominis]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GVRARSKCSRCKAVWYC--SRECQ-----VKHWA
THKKSCRDMVQTTVSESVVEPKLPEK----------------------------------
------------------------EGLKVTEEDKRVVERVTTSIKPVVVEREYVREVDAK
EVTSEERKPKRKSLFRQKFEKGLNYHCLFQSPGMSEVDEIISNMP--------VHYAGFR
KEKGCRIPDSDIE----------RSIPPRIKEVTRF--LDLFEEINVMKADLES------
------QDFIQDCQITL--DVRNSED---------STPDSTDVILRVDVKE----R----
-------------RGFKPDVILVDT-VDKEEVML--------------------------
-GLSESYVNLTN-----------KLDILKASAAYGIFNG--DS-SFGIQYKTPKSLF---
-RLPL--QL-------------------------SL--DHEIK-----------------
---------NRVVDSGVTTYADTATLSLGTR---SQHFW--------------------L
DVFWSWRDMSPFG--DIDEERIRNSYCSST--------------------MLRECRPSLG
SGVALRFE-HG--KLTALFPAQGHQLRGKLTYFGL--AGDVHA-LKCEGDAEFF-----Q
------------------------------ALSPRIRSQPGLLLHFRGKAGCLLPL----
------------------------NKRKSRFYDRFFLGR-QYVTGFERGSFGPRSAP---
----------------------------------------------EGERKQGDLLGGDC
CGTAGMELSLPLG-----------------------------------------------
---------------------------VGRARCRAFYE----------------------
------------------------------------------------------------
----R-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Blastocystis_hominis_gi|300121846|emb|CBK22420.2| Sam50 [Blastocystis hominis]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------SMPD-----------------------------------
------------------------------------------------------------
----------------------------------------ISGMP--------MNFSAFK
IEPPYKTKNRVIQ----------REIPEELKHAKTL--GEIYAALVKMQMNLMS------
------LDIFDDVRFVL--DVPDY-----------MQFDPNAVMVRMFLKE----K----
-------------RPVMLGVGGS-FSSTATDASL--------------------------
-EGNLEVVNATG-----------YADRLVSRVNFDVLRK--SS-LYSINLLVPKSIF---
-GHHL-----------------------------ILDYTKSIR-----------------
---------DYLKESSVSCLSDGVTLSLQHP---SRLYS--------------------F
AYSLAWRDMLPASNVDVDVERRSLQHVSRA--------------------MLRQCRPSLK
STLSASISLDS--RDNPVLPTSGSSLRLQ-------------------------------
-----------------------------------------LVSTFP-------------
--------------------------------------------RFDGRRTAGSSAT---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
